### PR TITLE
user data added to context

### PR DESCRIPTION
**Pull request by dabit1**
With this PR we'll be able to get the decoded user data from context. So in the resolvers we can get user data like this:

```javascript
me: (parent, args, { user }) => {
      console.log(user.id);
},
```

### CODE REVIEW

**Comment by bionicles** [comment]
Merge please, then we can make @user directive

**Comment by mohamedGamalAbuGalala** [comment]
Any updates on this :thinking:

**Review by johnymontana — APPROVED** [review]

**Comment by johnymontana** [comment]
Good idea, thanks @dabit1!

**Comment by mohamedGamalAbuGalala** [comment]
This needs to be updated in the `README.md` file

**Pull request merged**
